Event card
svs-ong/svs-website pull request #12
Opened 2024-10-09 17:14 UTC by Nim000

2024-10-11 16:33 UTC, Axetyy commented
The Image doesn't fit well, also why delete everything in About Us?

2024-10-19 09:07 UTC, baragan30 commented
Please try to merge this branch to development branch not to main branch

2024-10-19 09:08 UTC, baragan30 requested changes

2024-10-19 09:08 UTC, baragan30 commented on src/app/about/page.tsx
> +import { Button, Container, Stack, Typography } from '@mui/material';
We don't need so many imports. Delete them

2024-10-19 09:08 UTC, baragan30 commented on src/app/about/page.tsx
>    return (
Don't all comment all the existing features . Try to integrate yours in what exists. I think the place of the Event Card is in the our events page not in about us page. What do you think? Please create that page!

2024-10-19 12:28 UTC, closed without merging