value section structure according to figma
svs-ong/svs-website pull request #9
Opened 2024-10-01 13:04 UTC by allexa3

2024-10-01 14:25 UTC, Axetyy approved these changes
Good, I would have liked to see some dummy text / images to verify it works properly but this will do

2024-10-02 12:19 UTC, andrei-baragan requested changes

2024-10-02 12:19 UTC, andrei-baragan commented on .prettierrc.js
> +  trailingComma: '  all',
why do we need this space in '  all' ?

2024-10-02 12:19 UTC, andrei-baragan commented on src/components/organism/OurValuesSection/OurValuesSection.tsx
> +'use client';
I like the way you arrange things.

2024-10-02 12:19 UTC, andrei-baragan commented on src/components/organism/OurValuesSection/OurValuesSection.tsx
> +                        sx={{
Try to make this container to take all available space the Stack provides. In general it's bad practice to have big sizes like 300px because it's not responsive :). Let's keep just the padding and margins as constants and make big components like this to get it's size from parent.

2024-10-02 12:19 UTC, andrei-baragan commented on src/components/organism/OurValuesSection/OurValuesSection.tsx
> +export const OurValuesSection: React.FC<OurValuesSectionProps> = ({ title }) => {
It makes more sens to have a component named Value Card or other that takes a image, an title and a description as parameter. Then we will use this component in OurValuesSection  for Each Value that we receive :))

2024-10-03 10:05 UTC, andrei-baragan approved these changes
Just one line to remove before merge

2024-10-03 10:05 UTC, andrei-baragan commented on src/app/about/page.tsx
>      // </Stack>
Remove this commented code

2024-10-06 16:35 UTC, merged